const wikimedia = (file) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${file}`;

window.travelDestinations = [
  {
    id: 1,
    name: 'Goa',
    region: 'Goa • West India',
    description: 'Sunny beaches, lively markets, and relaxed coastal stays that fit short budget breaks.',
    budget: 'Low',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹7,500 - ₹11,000 per person',
    hotels: ['Ocean Crest Inn', 'Palm Stay Goa', 'Casa Breeze Lodge'],
    food: ['Goan fish curry', 'Prawn balchão', 'Bebinca dessert'],
    places: ['Baga Beach', 'Aguada Fort', 'Fontainhas', 'Anjuna Flea Market'],
    package: ['Day 1: Beach time and sunset views', 'Day 2: Fort visit and market shopping', 'Day 3: Watersports or heritage walk before departure'],
    dailyCost: 2600,
    transportBase: 1200,
    image: wikimedia('India_Goa_Big_Vagator_Beach_with_Fort_Chapora.jpg')
  },
  {
    id: 2,
    name: 'Jaipur',
    region: 'Rajasthan • North-West India',
    description: 'Royal forts, colorful bazaars, and heritage streets with good-value stays for city breaks.',
    budget: 'Medium',
    daysCategory: '4-5 Days',
    suggestedDuration: '4–5 Days',
    budgetEstimate: '₹11,000 - ₹16,500 per person',
    hotels: ['Pink City Haveli', 'Amber View Residency', 'Rajasthali Comfort'],
    food: ['Dal baati churma', 'Pyaaz kachori', 'Kulhad lassi'],
    places: ['Hawa Mahal', 'Amber Fort', 'City Palace', 'Nahargarh Fort'],
    package: ['Day 1: Hawa Mahal and City Palace', 'Day 2: Amber Fort and Jal Mahal', 'Day 3: Bazaar walk and local food trail', 'Day 4: Fort viewpoints and museums'],
    dailyCost: 3200,
    transportBase: 1800,
    image: wikimedia('Jaipur,_India,_Hawa_Mahal_Palace.jpg')
  },
  {
    id: 3,
    name: 'Manali',
    region: 'Himachal Pradesh • North India',
    description: 'Cool mountain weather, valley views, and adventure-friendly stays around the Beas river.',
    budget: 'Medium',
    daysCategory: '4-5 Days',
    suggestedDuration: '4–5 Days',
    budgetEstimate: '₹13,000 - ₹19,000 per person',
    hotels: ['Valley Nest Resort', 'Snowline Retreat', 'Cedar Trails Hotel'],
    food: ['Hot momos', 'Trout dishes', 'Bakery breakfasts'],
    places: ['Solang Valley', 'Old Manali', 'Hadimba Temple', 'Mall Road'],
    package: ['Day 1: Check-in and Old Manali walk', 'Day 2: Solang Valley adventure day', 'Day 3: Temple circuit and cafés', 'Day 4: Riverside leisure and shopping'],
    dailyCost: 3600,
    transportBase: 2100,
    image: wikimedia('Manali_City.jpg')
  },
  {
    id: 4,
    name: 'Udaipur',
    region: 'Rajasthan • West India',
    description: 'Lakefront palace views, romantic old streets, and elegant stays for scenic short holidays.',
    budget: 'High',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹14,000 - ₹21,000 per person',
    hotels: ['Lakeview Heritage Stay', 'Mewar Court Hotel', 'Royal Terrace Inn'],
    food: ['Rajasthani thali', 'Laal maas', 'Rooftop café dining'],
    places: ['Lake Pichola', 'City Palace', 'Saheliyon Ki Bari', 'Bagore Ki Haveli'],
    package: ['Day 1: Lake cruise and old city walk', 'Day 2: City Palace and local markets', 'Day 3: Garden visits and scenic brunch'],
    dailyCost: 4300,
    transportBase: 2400,
    image: 'https://sspark.genspark.ai/cfimages?u1=1emOIuNOrgFJ8kRNJINhLcdVwvWdhFwOPP0rjEHbBIgUImsfTto6t9uMNE6NSAMF76nTNzwWus%2BZOirkN565pzsIpzCJzjpFc5o8psBK3hIasorEpnYxvN57&u2=0uSidYI4klxWS0H3&width=2560'
  },
  {
    id: 5,
    name: 'Rishikesh',
    region: 'Uttarakhand • North India',
    description: 'Riverfront spirituality, yoga cafés, and adventure activities at a backpacker-friendly budget.',
    budget: 'Low',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹6,500 - ₹10,000 per person',
    hotels: ['Ganga Bliss Hostel', 'Yoga Retreat House', 'Riverstone Stay'],
    food: ['Healthy café bowls', 'Aloo puri', 'Ayurvedic thalis'],
    places: ['Laxman Jhula', 'Triveni Ghat', 'River rafting point', 'Beatles Ashram'],
    package: ['Day 1: Ghat walk and aarti', 'Day 2: Rafting and riverside cafés', 'Day 3: Ashram visit and yoga session'],
    dailyCost: 2400,
    transportBase: 1000,
    image: wikimedia('Lakshman_Jhula,_Rishikesh,_Uttarakhand,_India.jpg')
  },
  {
    id: 6,
    name: 'Mysore',
    region: 'Karnataka • South India',
    description: 'Palace charm, relaxed city pace, and food-rich short breaks with affordable city travel.',
    budget: 'Low',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹7,000 - ₹10,500 per person',
    hotels: ['Royal Orchid Budget Stay', 'Silk Route Inn', 'Garden Square Lodge'],
    food: ['Mysore masala dosa', 'Filter coffee', 'Mysore pak'],
    places: ['Mysore Palace', 'Chamundi Hills', 'Brindavan Gardens', 'Devaraja Market'],
    package: ['Day 1: Palace tour and market visit', 'Day 2: Chamundi Hills and gardens', 'Day 3: Museum stop and food trail'],
    dailyCost: 2500,
    transportBase: 900,
    image: wikimedia('Mysore_Palace,_Mysuru.jpg')
  },
  {
    id: 7,
    name: 'Darjeeling',
    region: 'West Bengal • East India',
    description: 'Tea gardens, Himalayan viewpoints, and cozy hill-town stays suited for scenic escapes.',
    budget: 'Medium',
    daysCategory: '4-5 Days',
    suggestedDuration: '4–5 Days',
    budgetEstimate: '₹12,500 - ₹18,500 per person',
    hotels: ['Tea View Residency', 'Cloudline Cottage', 'Summit Comfort Darjeeling'],
    food: ['Steamed momos', 'Thukpa', 'Fresh tea tastings'],
    places: ['Tiger Hill', 'Batasia Loop', 'Tea Estate', 'Mall Road'],
    package: ['Day 1: Mall Road and café evening', 'Day 2: Tiger Hill sunrise', 'Day 3: Tea estate tour', 'Day 4: Monastery and market walk'],
    dailyCost: 3400,
    transportBase: 1900,
    image: wikimedia('Landscape_of_Darjeeling,India.jpg')
  },
  {
    id: 8,
    name: 'Pondicherry',
    region: 'Puducherry • South India',
    description: 'French-style lanes, seaside walks, and calm weekend itineraries with boutique stays.',
    budget: 'High',
    daysCategory: '4-5 Days',
    suggestedDuration: '4–5 Days',
    budgetEstimate: '₹15,000 - ₹22,500 per person',
    hotels: ['Seaside Boutique Inn', 'French Quarter Stay', 'Azure Bay Hotel'],
    food: ['Creole cuisine', 'Fresh croissants', 'Seafood platters'],
    places: ['Promenade Beach', 'White Town', 'Auroville', 'Paradise Beach'],
    package: ['Day 1: White Town heritage walk', 'Day 2: Beach day and cafés', 'Day 3: Auroville exploration', 'Day 4: Leisure cycling and shopping'],
    dailyCost: 4100,
    transportBase: 2200,
    image: wikimedia('Pondicherry,_India.jpg')
  },
  {
    id: 9,
    name: 'Delhi',
    region: 'Delhi NCR • North India',
    description: 'Historic monuments, bustling markets, and diverse food trails for quick urban trips.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹8,500 - ₹13,500 per person',
    hotels: ['Central Vista Stay', 'Karol Bagh Residency', 'Heritage Gate Hotel'],
    food: ['Chole bhature', 'Butter chicken', 'Street chaat'],
    places: ['India Gate', 'Red Fort', 'Humayun’s Tomb', 'Connaught Place'],
    package: ['Day 1: Central Delhi landmarks', 'Day 2: Old Delhi food trail', 'Day 3: Museums and markets'],
    dailyCost: 3000,
    transportBase: 1700,
    image: wikimedia('Delhi,_India,_India_Gate.jpg')
  },
  {
    id: 10,
    name: 'Mumbai',
    region: 'Maharashtra • West India',
    description: 'Seafront city energy, colonial landmarks, and iconic food stops for a busy city break.',
    budget: 'High',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹14,000 - ₹20,500 per person',
    hotels: ['Marine Drive Stay', 'Colaba Harbour Inn', 'Cityline Residency'],
    food: ['Vada pav', 'Bombay sandwich', 'Seafood thali'],
    places: ['Gateway of India', 'Marine Drive', 'Colaba Causeway', 'Bandra Bandstand'],
    package: ['Day 1: South Mumbai circuit', 'Day 2: Bandra and seaside sunset', 'Day 3: Museum visit and shopping'],
    dailyCost: 4600,
    transportBase: 2300,
    image: wikimedia('Gateway_of_India,_Mumbai,_IN.jpg')
  },
  {
    id: 11,
    name: 'Hyderabad',
    region: 'Telangana • South-Central India',
    description: 'Historic bazaars, biryani hotspots, and old-city landmarks mixed with modern city views.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹9,000 - ₹14,000 per person',
    hotels: ['Charminar Court', 'Hussain Sagar Stay', 'Banjara Comfort'],
    food: ['Hyderabadi biryani', 'Irani chai', 'Qubani ka meetha'],
    places: ['Charminar', 'Golconda Fort', 'Hussain Sagar', 'Laad Bazaar'],
    package: ['Day 1: Old city and Charminar', 'Day 2: Fort visit and lakefront', 'Day 3: Shopping and food crawl'],
    dailyCost: 3100,
    transportBase: 1500,
    image: 'https://sspark.genspark.ai/cfimages?u1=ncGAzYD965MQXIqHZtDWr7%2BTS%2BVtjnqQh1eddHLrjz5PQvvqNiek7R6gA%2BfkSnLlHIhXWJeKDO8MS4pp5QecZLxAkR%2BPg636VbTw2XZukHhfgWxD5gkeWdzOrC5dPmVLgk4Ebq3BB1XZgg7D8C%2F0ETFFe0FmhpaG3kTJrjnPUQ6qQ2dIoVMwXtkKRmSUWmAgsleUjzfh1aHFmTodtynE9Q%3D%3D&u2=f%2F32OrdLHCGL72wd&width=2560'
  },
  {
    id: 12,
    name: 'Ooty',
    region: 'Tamil Nadu • South India',
    description: 'Tea estates, cool weather, and classic hill-station scenery for relaxed mountain holidays.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹9,500 - ₹14,500 per person',
    hotels: ['Blue Hills Cottage', 'Nilgiri Valley Inn', 'Botanical Stay'],
    food: ['Homestyle South Indian meals', 'Fresh chocolates', 'Hot tea snacks'],
    places: ['Ooty Lake', 'Botanical Garden', 'Doddabetta Peak', 'Tea Factory'],
    package: ['Day 1: Lake and town walk', 'Day 2: Peak view and gardens', 'Day 3: Tea factory and shopping'],
    dailyCost: 3200,
    transportBase: 1500,
    image: wikimedia('Ooty_tamilnadu_india.jpg')
  },
  {
    id: 13,
    name: 'Munnar',
    region: 'Kerala • South India',
    description: 'Rolling tea plantations, scenic drives, and misty hill views perfect for quiet escapes.',
    budget: 'Medium',
    daysCategory: '4-5 Days',
    suggestedDuration: '4–5 Days',
    budgetEstimate: '₹12,000 - ₹18,000 per person',
    hotels: ['Tea Garden Retreat', 'Cloud Leaf Resort', 'High Range Stay'],
    food: ['Kerala meals', 'Appam and stew', 'Spiced tea snacks'],
    places: ['Tea Gardens', 'Top Station', 'Mattupetty Dam', 'Eravikulam National Park'],
    package: ['Day 1: Tea garden viewpoints', 'Day 2: Dam and boating', 'Day 3: National park visit', 'Day 4: Local spice shopping'],
    dailyCost: 3500,
    transportBase: 1900,
    image: wikimedia('Tea_Fields_Of_Munnar,_Kerala,_India.jpg')
  },
  {
    id: 14,
    name: 'Varanasi',
    region: 'Uttar Pradesh • North India',
    description: 'Ancient ghats, spiritual rituals, and cultural walks along the Ganges riverfront.',
    budget: 'Low',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹7,000 - ₹10,500 per person',
    hotels: ['Ghat View Residency', 'Kashi Comfort Stay', 'River Heritage Rooms'],
    food: ['Kachori sabzi', 'Banarasi chai', 'Malaiyyo'],
    places: ['Dashashwamedh Ghat', 'Assi Ghat', 'Kashi Vishwanath Corridor', 'Sarnath'],
    package: ['Day 1: Evening aarti and ghat walk', 'Day 2: Sunrise boat ride and temple area', 'Day 3: Sarnath and food trail'],
    dailyCost: 2500,
    transportBase: 1100,
    image: wikimedia('Varanasi,_India_(47307281102).jpg')
  },
  {
    id: 15,
    name: 'Amritsar',
    region: 'Punjab • North India',
    description: 'Golden Temple serenity, Punjabi food, and compact sightseeing around a welcoming old city.',
    budget: 'Low',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹7,500 - ₹11,500 per person',
    hotels: ['Heritage Temple Stay', 'Punjabi Court Inn', 'Amritsar Central Rooms'],
    food: ['Amritsari kulcha', 'Lassi', 'Langar meal'],
    places: ['Golden Temple', 'Jallianwala Bagh', 'Wagah Border', 'Hall Bazaar'],
    package: ['Day 1: Golden Temple and old city', 'Day 2: Local food trail and memorials', 'Day 3: Wagah ceremony'],
    dailyCost: 2700,
    transportBase: 1200,
    image: wikimedia('Golden_Temple_-_Amritsar_India.jpg')
  },
  {
    id: 16,
    name: 'Srinagar',
    region: 'Jammu & Kashmir • North India',
    description: 'Dal Lake houseboats, mountain-backed gardens, and classic Kashmir scenery.',
    budget: 'High',
    daysCategory: '4-5 Days',
    suggestedDuration: '4–5 Days',
    budgetEstimate: '₹16,000 - ₹24,000 per person',
    hotels: ['Dal View Houseboat', 'Boulevard Lakeside', 'Kashmir Valley Inn'],
    food: ['Kahwa', 'Rogan josh', 'Gushtaba'],
    places: ['Dal Lake', 'Mughal Gardens', 'Shankaracharya Temple', 'Nishat Bagh'],
    package: ['Day 1: Houseboat check-in and shikara ride', 'Day 2: Garden circuit', 'Day 3: Old city and handicrafts', 'Day 4: Day trip or leisure on the lake'],
    dailyCost: 4700,
    transportBase: 2600,
    image: wikimedia('View_of_Dal_lake_Srinagar.jpg')
  },
  {
    id: 17,
    name: 'Leh',
    region: 'Ladakh • North India',
    description: 'High-altitude desert views, monasteries, and dramatic mountain roads for adventure seekers.',
    budget: 'High',
    daysCategory: '4-5 Days',
    suggestedDuration: '4–5 Days',
    budgetEstimate: '₹18,000 - ₹28,000 per person',
    hotels: ['Stok View Stay', 'Ladakh Horizon Inn', 'Monastery Road Lodge'],
    food: ['Thukpa', 'Butter tea', 'Skyu'],
    places: ['Shanti Stupa', 'Leh Palace', 'Magnetic Hill', 'Khardung La'],
    package: ['Day 1: Acclimatization and local market', 'Day 2: Monasteries and palace', 'Day 3: Khardung La drive', 'Day 4: Scenic viewpoints and cafés'],
    dailyCost: 5200,
    transportBase: 3000,
    image: wikimedia('Leh,_Ladakh,_India.jpg')
  },
  {
    id: 18,
    name: 'Chandigarh',
    region: 'Chandigarh • North India',
    description: 'Planned city boulevards, architecture landmarks, and calm lakefront spaces for urban breaks.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹8,500 - ₹13,000 per person',
    hotels: ['Sector 17 Stay', 'Capitol Comfort', 'Lakeview Chandigarh Inn'],
    food: ['North Indian thali', 'Street golgappa', 'Punjabi breakfast platters'],
    places: ['Rock Garden', 'Sukhna Lake', 'Capitol Complex', 'Rose Garden'],
    package: ['Day 1: Rock Garden and Sukhna Lake', 'Day 2: Capitol Complex and markets', 'Day 3: Leisure cafés and gardens'],
    dailyCost: 2900,
    transportBase: 1400,
    image: wikimedia('Open_hand_monument_of_Chandigarh,_India.jpg')
  },
  {
    id: 19,
    name: 'Rann of Kutch',
    region: 'Gujarat • West India',
    description: 'White salt desert landscapes, festival vibes, and unique sunrise-sunset experiences.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹10,500 - ₹15,500 per person',
    hotels: ['White Desert Camp', 'Kutch Eco Stay', 'Bhuj Gateway Inn'],
    food: ['Kutchi thali', 'Bajra rotla', 'Masala chaas'],
    places: ['White Rann', 'Kala Dungar', 'Kutch Museum', 'Craft villages'],
    package: ['Day 1: Bhuj arrival and craft trail', 'Day 2: White Rann sunset', 'Day 3: Local markets and departure'],
    dailyCost: 3300,
    transportBase: 2100,
    image: wikimedia('White_Rann_of_Kutch.jpg')
  },
  {
    id: 20,
    name: 'Puri',
    region: 'Odisha • East India',
    description: 'Temple heritage, sea beach views, and affordable coastal pilgrim-city travel.',
    budget: 'Low',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹6,500 - ₹10,500 per person',
    hotels: ['Sea Beach Residency', 'Jagannath Comfort Inn', 'Temple View Lodge'],
    food: ['Mahaprasad', 'Seafood fry', 'Odia sweets'],
    places: ['Puri Beach', 'Jagannath Temple area', 'Konark day trip', 'Swargadwar Market'],
    package: ['Day 1: Beachfront and temple area', 'Day 2: Konark excursion', 'Day 3: Market shopping and sunrise'],
    dailyCost: 2400,
    transportBase: 1100,
    image: wikimedia('Puri_Sea_Beach_viewed_from_the_light_house.jpg')
  },
  {
    id: 21,
    name: 'Khajuraho',
    region: 'Madhya Pradesh • Central India',
    description: 'UNESCO temple architecture, sculpture trails, and compact cultural sightseeing.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹8,500 - ₹13,500 per person',
    hotels: ['Temple Courtyard Stay', 'Bundelkhand Residency', 'Stone Art Inn'],
    food: ['Bundeli cuisine', 'Poha breakfast', 'Traditional thali'],
    places: ['Western Group of Temples', 'Kandariya Mahadev', 'Archaeological Museum', 'Light and Sound Show'],
    package: ['Day 1: Temple complex visit', 'Day 2: Museum and cultural show', 'Day 3: Nearby village and departure'],
    dailyCost: 3000,
    transportBase: 1700,
    image: wikimedia('A_view_of_Kandariya_Mahadev_Temple_Khajuraho_India.jpg')
  },
  {
    id: 22,
    name: 'Visakhapatnam',
    region: 'Andhra Pradesh • East India',
    description: 'Bay views, hilltop cityscapes, and beach roads ideal for quick coastal city trips.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹8,500 - ₹13,000 per person',
    hotels: ['Beach Road Stay', 'Kailasagiri View Inn', 'Vizag Bay Rooms'],
    food: ['Andhra meals', 'Prawn curry', 'Spicy street snacks'],
    places: ['RK Beach', 'Kailasagiri', 'Rushikonda Beach', 'Submarine Museum'],
    package: ['Day 1: Beach road and museum', 'Day 2: Hilltop views and café stops', 'Day 3: Rushikonda and local shopping'],
    dailyCost: 2900,
    transportBase: 1500,
    image: wikimedia('Vizag_aerial_view.jpg')
  },
  {
    id: 23,
    name: 'Bodh Gaya',
    region: 'Bihar • East India',
    description: 'Pilgrimage calm, monastery circuits, and heritage stays around the Mahabodhi Temple.',
    budget: 'Low',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹6,000 - ₹9,500 per person',
    hotels: ['Temple Garden Inn', 'Bodhi Retreat', 'Monastery Lane Stay'],
    food: ['Bihari thali', 'Litti chokha', 'Simple monastery meals'],
    places: ['Mahabodhi Temple', 'Great Buddha Statue', 'Thai Monastery', 'Meditation Park'],
    package: ['Day 1: Temple complex and meditation area', 'Day 2: Monastery circuit', 'Day 3: Local market and departure'],
    dailyCost: 2200,
    transportBase: 900,
    image: wikimedia('Mahabodhi_Temple_Bodh_Gaya_Bihar_India.jpg')
  },
  {
    id: 24,
    name: 'Kaziranga',
    region: 'Assam • North-East India',
    description: 'Wildlife safaris, grassland landscapes, and nature stays around India’s rhino reserve.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹10,000 - ₹15,000 per person',
    hotels: ['Rhino View Lodge', 'Safari Grassland Camp', 'Kaziranga Nature Stay'],
    food: ['Assamese thali', 'Smoked meat dishes', 'Pitha snacks'],
    places: ['Jeep Safari Zone', 'Elephant Safari point', 'Orchid Park', 'Tea garden drive'],
    package: ['Day 1: Arrival and local cultural stop', 'Day 2: Morning safari and park views', 'Day 3: Tea garden route and return'],
    dailyCost: 3400,
    transportBase: 2000,
    image: wikimedia('Beauty_of_Kaziranga_National_Park.jpg')
  },
  {
    id: 25,
    name: 'Tawang',
    region: 'Arunachal Pradesh • North-East India',
    description: 'Monastery views, high mountain roads, and serene lakes in a remote Himalayan setting.',
    budget: 'High',
    daysCategory: '4-5 Days',
    suggestedDuration: '4–5 Days',
    budgetEstimate: '₹17,000 - ₹25,500 per person',
    hotels: ['Monastery View Stay', 'Sela Route Lodge', 'Snow Peaks Residency'],
    food: ['Momos', 'Thenthuk', 'Butter tea'],
    places: ['Tawang Monastery', 'Sela Pass', 'Madhuri Lake', 'War Memorial'],
    package: ['Day 1: Scenic arrival and local market', 'Day 2: Monastery and memorial', 'Day 3: Sela Pass and lake', 'Day 4: Leisure and café stops'],
    dailyCost: 4500,
    transportBase: 2800,
    image: wikimedia('The_Tawang_Monastery.jpg')
  },
  {
    id: 26,
    name: 'Gangtok',
    region: 'Sikkim • North-East India',
    description: 'Hillside city views, monastery culture, and pedestrian-friendly streets around MG Marg.',
    budget: 'Medium',
    daysCategory: '4-5 Days',
    suggestedDuration: '4–5 Days',
    budgetEstimate: '₹12,500 - ₹18,500 per person',
    hotels: ['MG Marg View Inn', 'Ropeway Residency', 'Snowpeak Rooms'],
    food: ['Momos', 'Thukpa', 'Sikkimese platter'],
    places: ['MG Marg', 'Tashi View Point', 'Ropeway', 'Enchey Monastery'],
    package: ['Day 1: MG Marg and local cafés', 'Day 2: Monastery and viewpoints', 'Day 3: Ropeway and market walk', 'Day 4: Day trip or leisure city time'],
    dailyCost: 3500,
    transportBase: 2100,
    image: wikimedia('Gangtok_from_Tibet_Road.jpg')
  },
  {
    id: 27,
    name: 'Shillong',
    region: 'Meghalaya • North-East India',
    description: 'Lakes, rolling hills, and easy scenic drives around one of India’s most loved hill cities.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹9,500 - ₹14,500 per person',
    hotels: ['Pine Hill Stay', 'Shillong Lake Residency', 'Cloud Town Inn'],
    food: ['Jadoh', 'Dohneiiong', 'Café bakes'],
    places: ['Umiam Lake', 'Shillong Peak', 'Ward’s Lake', 'Police Bazaar'],
    package: ['Day 1: Umiam Lake and city stroll', 'Day 2: Peak viewpoints and cafés', 'Day 3: Market shopping and departure'],
    dailyCost: 3200,
    transportBase: 1700,
    image: wikimedia('Aerial_view_of_Shillong_Meghalaya_India.jpg')
  },
  {
    id: 28,
    name: 'Loktak Lake',
    region: 'Manipur • North-East India',
    description: 'Floating phumdis, peaceful lake scenery, and slow travel around a unique wetland ecosystem.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹9,000 - ₹13,500 per person',
    hotels: ['Moirang Lake Stay', 'Phumdi View Lodge', 'Loktak Eco Rooms'],
    food: ['Manipuri thali', 'Eromba', 'Rice-based local meals'],
    places: ['Sendra Viewpoint', 'Floating islands', 'Moirang town', 'Boat rides'],
    package: ['Day 1: Lake viewpoints and sunset', 'Day 2: Boat ride and Moirang circuit', 'Day 3: Local food stop and return'],
    dailyCost: 3000,
    transportBase: 1600,
    image: wikimedia('The_Loktak_Lake.jpg')
  },
  {
    id: 29,
    name: 'Kohima',
    region: 'Nagaland • North-East India',
    description: 'Hill town culture, war cemetery history, and scenic routes through the Naga highlands.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹9,500 - ₹14,000 per person',
    hotels: ['Highland Kohima Stay', 'War Cemetery Inn', 'Naga Hills Residency'],
    food: ['Smoked pork', 'Axone dishes', 'Rice platters'],
    places: ['Kohima War Cemetery', 'Cathedral', 'State Museum', 'Viewpoints'],
    package: ['Day 1: Town walk and viewpoints', 'Day 2: Museum and cemetery circuit', 'Day 3: Local market and café stop'],
    dailyCost: 3100,
    transportBase: 1700,
    image: wikimedia('Kohima_Nagaland_India.jpg')
  },
  {
    id: 30,
    name: 'Aizawl',
    region: 'Mizoram • North-East India',
    description: 'Terraced hill-city views, quiet streets, and scenic urban landscapes across the hills.',
    budget: 'Medium',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹9,000 - ₹13,000 per person',
    hotels: ['Hill Crest Aizawl', 'Panorama Residency', 'Mizoram View Inn'],
    food: ['Bai', 'Smoked meat dishes', 'Simple rice meals'],
    places: ['City viewpoints', 'Solomon’s Temple area', 'Local market', 'Hill drives'],
    package: ['Day 1: Panorama points and local cafés', 'Day 2: Temple area and city walk', 'Day 3: Market stop and return'],
    dailyCost: 2900,
    transportBase: 1600,
    image: wikimedia('Aizawl_panoramicview.jpg')
  },
  {
    id: 31,
    name: 'Agartala',
    region: 'Tripura • North-East India',
    description: 'Palaces, lakeside landmarks, and easy-paced city travel in Tripura’s heritage capital.',
    budget: 'Low',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹7,500 - ₹11,500 per person',
    hotels: ['Ujjayanta Stay', 'Agartala City Inn', 'Tripura Heritage Rooms'],
    food: ['Mui borok dishes', 'Rice platters', 'Local sweets'],
    places: ['Ujjayanta Palace', 'Neermahal day trip', 'Tripura State Museum', 'Local markets'],
    package: ['Day 1: Palace and museum circuit', 'Day 2: Neermahal excursion', 'Day 3: Market walk and departure'],
    dailyCost: 2600,
    transportBase: 1200,
    image: wikimedia('Neermahal,_Tripura_Agartala,_India.jpg')
  },
  {
    id: 32,
    name: 'Havelock Island',
    region: 'Andaman & Nicobar Islands • Island India',
    description: 'Turquoise waters, white-sand beaches, and tropical island stays for laid-back holidays.',
    budget: 'High',
    daysCategory: '4-5 Days',
    suggestedDuration: '4–5 Days',
    budgetEstimate: '₹18,000 - ₹27,000 per person',
    hotels: ['Radhanagar Bay Stay', 'Island Palm Resort', 'Lagoon Breeze Havelock'],
    food: ['Seafood platters', 'Coconut-based curries', 'Beach café meals'],
    places: ['Radhanagar Beach', 'Elephant Beach', 'Kalapathar Beach', 'Jetty area'],
    package: ['Day 1: Ferry arrival and beach sunset', 'Day 2: Snorkeling and island cafés', 'Day 3: Kalapathar and leisure time', 'Day 4: Optional water activities'],
    dailyCost: 5200,
    transportBase: 3400,
    image: 'https://sspark.genspark.ai/cfimages?u1=MzJV7Z3JEGZbptPcUXYI9HPircKVuTTyqmR6DB5jfBDk%2BS3vHNnWE%2Fhp0K%2FvGCuqT3ZO1gUsIgkoDlUFF48%2BT77kHwEGGyYdBjn511dvaMmFBmGfrz8woTrzfq%2BrvCUshZvcJH%2F28BfrML0%3D&u2=MY3gXblJ16ZLhE%2Bt&width=2560'
  },
  {
    id: 33,
    name: 'Lakshadweep',
    region: 'Lakshadweep • Island India',
    description: 'Clear lagoons, coral island scenery, and slow tropical travel for premium beach escapes.',
    budget: 'High',
    daysCategory: '4-5 Days',
    suggestedDuration: '4–5 Days',
    budgetEstimate: '₹20,000 - ₹30,000 per person',
    hotels: ['Lagoon Retreat', 'Agatti Sea Stay', 'Island Coral Resort'],
    food: ['Fresh seafood', 'Coconut rice dishes', 'Island-style curries'],
    places: ['Agatti Island', 'Bangaram Island', 'Kavaratti Beach', 'Lagoon viewpoints'],
    package: ['Day 1: Island arrival and lagoon walk', 'Day 2: Beach leisure and boat ride', 'Day 3: Snorkeling or reef time', 'Day 4: Island exploration'],
    dailyCost: 5600,
    transportBase: 3600,
    image: wikimedia('Lakshadweep_-_Agatti_Islands.jpg')
  },
  {
    id: 34,
    name: 'Daman',
    region: 'Dadra & Nagar Haveli and Daman & Diu • West India',
    description: 'Quiet beaches, Portuguese-era heritage, and easy weekend plans near the western coast.',
    budget: 'Low',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹7,000 - ₹10,500 per person',
    hotels: ['Jampore Beach Inn', 'Moti Daman Stay', 'Sea Breeze Daman'],
    food: ['Seafood curry', 'Portuguese-style bakes', 'Coastal snacks'],
    places: ['Jampore Beach', 'Moti Daman Fort', 'Lighthouse area', 'Church district'],
    package: ['Day 1: Beach and sunset', 'Day 2: Fort circuit and heritage walk', 'Day 3: Leisure breakfast and departure'],
    dailyCost: 2500,
    transportBase: 1000,
    image: wikimedia('Jampore_beach_,Daman,_India.jpg')
  },
  {
    id: 35,
    name: 'Netarhat',
    region: 'Jharkhand • East India',
    description: 'Forest roads, pine-covered hills, and peaceful viewpoints in a less-crowded hill station.',
    budget: 'Low',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹6,500 - ₹9,500 per person',
    hotels: ['Forest Hill Stay', 'Netarhat View Lodge', 'Pine Breeze Rooms'],
    food: ['Simple local thali', 'Tea and snacks', 'Homestyle meals'],
    places: ['Magnolia Point', 'Pine forest area', 'Waterfalls', 'Sunrise viewpoint'],
    package: ['Day 1: Pine forest and sunset point', 'Day 2: Waterfall circuit', 'Day 3: Sunrise and return'],
    dailyCost: 2200,
    transportBase: 900,
    image: wikimedia('Pine_trees_of_Netarhat_Hill_station.jpg')
  },
  {
    id: 36,
    name: 'Kurukshetra',
    region: 'Haryana • North India',
    description: 'Sacred lake sites, Mahabharata heritage landmarks, and straightforward short pilgrim trips.',
    budget: 'Low',
    daysCategory: '2-3 Days',
    suggestedDuration: '2–3 Days',
    budgetEstimate: '₹6,500 - ₹10,000 per person',
    hotels: ['Sarovar View Stay', 'Kurukshetra Comfort Inn', 'Jyotisar Residency'],
    food: ['North Indian thali', 'Kheer prasad', 'Street snacks'],
    places: ['Brahma Sarovar', 'Jyotisar', 'Sheikh Chilli Tomb', 'Panorama and Science Centre'],
    package: ['Day 1: Sarovar and temple circuit', 'Day 2: Heritage sites and local food', 'Day 3: Museum stop and departure'],
    dailyCost: 2300,
    transportBase: 950,
    image: wikimedia('Brahma_Sarovar_Kurukshetra.jpg')
  }
];
